import os
import time

os.system("clear")
print("#########################")
print("# INSTALLATION DE NGINX #")
print("#########################")
print(" ")
time.sleep(2)
os.system("python3 2.py")
time.sleep(2)
os.system("clear")

os.system("clear")
print("#########################")
print("# INSTALLATION D'APACHE #")
print("#########################")
print(" ")
time.sleep(2)
os.system("python3 8.py")
time.sleep(2)
os.system("clear")

print("###########################")
print("# INSTALLATION DE MONGODB #")
print("###########################")
print(" ")
time.sleep(2)
os.system("python3 3.py")
time.sleep(2)
os.system("clear")

os.system("clear")
print("#########################")
print("# INSTALLATION MARIADB  #")
print("#########################")
print(" ")
time.sleep(2)
os.system("python3 9.py")
time.sleep(2)
os.system("clear")

print("########################")
print("# INSTALLATION DE NMON #")
print("########################")
print(" ")
time.sleep(2)
os.system("python3 4.py")
time.sleep(2)
os.system("clear")

print("############################")
print("# INSTALLATION DE FAIL2BAN #")
print("############################")
print(" ")
time.sleep(2)
os.system("python3 5.py")
time.sleep(2)
os.system("clear")

print("####################################")
print("# INSTALLATION DE FLASK / GUNICORN #")
print("####################################")
print(" ")
time.sleep(2)
os.system("python3 7.py")
time.sleep(2)
os.system("clear")

print("#################################")
print("#      INSTALL MINICONDA        #")
print("#################################")
print(" ")
time.sleep(2)
os.system("bash 101.sh -b -p $home/test/miniconda -u")
time.sleep(2)
os.system("clear")

print("#######################")
print("# SECURISATION DU SSH #")
print("#######################")
print(" ")
time.sleep(2)
os.system("python3 99.py")
time.sleep(2)
os.system("clear")

print("#################################")
print("# AJOUT DE L'UTILISATEUR techIA #")
print("#################################")
print(" ")
time.sleep(2)
os.system('sh 100.sh')                  ### /!\ EDITER LE MOT DE PASSE DANS CE FICHIER!! /!\ ##
os.system("usermod -aG sudo techIA")
os.system("mkdir -p /run/sshd")
os.system("service ssh restart")
time.sleep(2)
os.system("clear")

print("###########################")
print("# DAEMON SERVICE GUNICORN #")
print("###########################")
print(" ")
time.sleep(2)
os.system("python3 101.py")
time.sleep(2)
os.system("clear")


